In [1]:
# 第一题
import numpy as np
#第二题:打印numpy的版本和配置说明
print(np.__version__)

1.15.4


In [2]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/admin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/admin/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/admin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/U

In [3]:
# 第三题
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#第四题
a = np.ones(10)
print("{} bytes".format(a.size * a.itemsize))  # print("%d bytes" % (a.size * a.itemsize))

80 bytes


In [5]:
# 第五题：从命令行得到numpy中的add函数说明文档
numpy.info(numpy.add)

NameError: name 'numpy' is not defined

In [6]:
# 第六题
b = np.zeros(10)
z[4]= 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# 第七题
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:


# 第八题：反转向量
c = np.arange(10)
c = c[::-1]
print(c)

[9 8 7 6 5 4 3 2 1 0]


In [9]:
# 第九题
d = np.arange(9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# 第十题:找到数组中非0元素的位置索引
e = np.nonzero([1,2,0,3,4,5,6])
print(e)

(array([0, 1, 3, 4, 5, 6], dtype=int64),)


In [11]:
# 第十一题
f = np.eye(3)   # z = np.identity(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# 第十二题
g = np.random.random((3,3,3))
print(g)

[[[0.05565105 0.46901252 0.90949456]
  [0.55617023 0.63564265 0.05924595]
  [0.61375205 0.69712485 0.6507869 ]]

 [[0.31100818 0.21124357 0.6343163 ]
  [0.67599862 0.02443215 0.16335588]
  [0.04765589 0.63555822 0.06854505]]

 [[0.13827649 0.5415321  0.96430727]
  [0.30855629 0.81643603 0.90712927]
  [0.88166679 0.34153259 0.58677273]]]


In [13]:
#第十三题
h = np.random.random((10,10))
hmin,hmax = h.min(),h.max()
print(hmin,hmax)


0.02046440423687368 0.9932051587935903


In [14]:
# 第十四题: 找数组的平均值
j = np.random.random(30)
print(j)

[0.22583492 0.52550398 0.97011885 0.90163835 0.54556526 0.18399067
 0.0415577  0.03522005 0.72733149 0.54130268 0.6151101  0.00842939
 0.66291179 0.96513131 0.88221945 0.86521824 0.24329244 0.11036989
 0.86520436 0.75686944 0.32887948 0.01388406 0.26699035 0.94177369
 0.09417108 0.16905999 0.03420757 0.7117102  0.84034035 0.29750258]


In [15]:
k = j.mean()
k

0.47904465701364657

In [16]:
# 第十五题: 创建一个边界值为1，其余为0的二维数组
l = np.ones((10,10))
l[1:-1,1:-1] = 0
l

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
# 第十六题： 对于一个存在的二维数组，如何添加一个用0填充的边界
z = np.ones((5,5))
z = np.pad(z,pad_width = 1,mode = 'constant',constant_values = 0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [18]:


# 第十七题：运行以下表达式
print(0*np.nan)


nan


In [19]:
print(np.nan == np.nan)

False


In [20]:
print(np.inf > np.nan)

False


In [21]:
print(np.nan - np.nan)

nan


In [22]:
print(0.3 == 3*0.1)

False


In [23]:
# 第十八题:创建一个5 x 5 的矩阵，并设置1，2，3，4落在其对角线下方的位置
m = np.diag(1+np.arange(4),k = -1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [24]:
# 第十九题：创建一个8x8的矩阵，并设置为棋盘样式
z = np.zeros((8,8),dtype = int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
# 第二十题:输出数组的第100个元素的索引
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [26]:
#第二十一题:用tile函数创建第十九题的矩阵
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#第二十二题：对一个5x5的随机矩阵做归一化
z = np.random.random((5,5))
zmax,zmin = z.max(),z.min()
z = (z - zmin) / (zmax - zmin)
print(z)

[[1.         0.42893506 0.28903828 0.36851381 0.00340021]
 [0.10361993 0.35688315 0.87645965 0.6614976  0.90377274]
 [0.34772626 0.92514787 0.0270636  0.95877803 0.89384399]
 [0.19840003 0.00926153 0.53744819 0.22434506 0.99004912]
 [0.65980879 0.90908904 0.         0.38460427 0.30956133]]


In [28]:
# 第二十三题：创建一个将颜色描述为（rgba）四个无符号字节的自定义dtype
color = np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [29]:
#第二十四题
z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [30]:
#第二十五题
z = np.arange(12)
z[(z>3)&(z<=8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11]


In [31]:
# 第二十六题:  ??
print(sum(range(5),-1))

9


In [32]:

from numpy import *
print(sum(range(5),-1))

10


In [33]:
# 第二十七题
z = np.arange(5)
z**z

array([  1,   1,   4,  27, 256], dtype=int32)

In [34]:
z = np.arange(5)
2<<z>>2

array([0, 1, 2, 4, 8], dtype=int32)

In [35]:
z = np.arange(5)
z < -z

array([False, False, False, False, False])

In [36]:
z = np.arange(5)
1j*z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [38]:
z = np.arange(5)
z/ 1 /1

array([0., 1., 2., 3., 4.])

In [40]:
z = np.arange(5)
z<z


array([False, False, False, False, False])

In [41]:
#第二十八题
print(np.array(0) / np.array(0))


nan


C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [42]:
print(np.array(0) // np.array(0))


0


C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [44]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [46]:
# 第二十九题：如何从零位对浮点数组做舍入
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[-1. -1.  2. -7.  9. -7.  2.  7. -8.  9.]


In [52]:
# 第三十题：如何找到两个数组的共同元素
z1 = np.random.randn(0,10,10)
z2 = np.random.randn(0,10,10)
print(np.intersect1d(z1,z2))

[]


In [56]:
#第三十一题：如何忽略所有numpy的警告
defaults = np.seterr(all = "ignore")
z = np.ones(1) / 0
_ = np.seterr(**defaults)

# An equivalent way,with a context manager:

with np.errstate(divide="ignore"):
    z = np.ones(1) / 0
z

array([inf])

In [57]:
#第三十二题
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [62]:
# 第三十三题：如何得到昨天，今天，明天的日期
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("yesterday is " + str(yesterday))
print("today is "+ str(today))
print("tomorrow" + str(tomorrow))

yesterday is 2019-08-06
today is 2019-08-07
tomorrow2019-08-08


In [63]:
# 第三十四题:如何得到所有与2016年7月对应的日期
z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [64]:
# 第三十五题：如何在位计算（A + B）、*（-A/2）
a = np.ones(3)*1
b = np.ones(3)*2
c = np.ones(3)*3
np.add(a,b,out = b)



array([3., 3., 3.])

In [65]:
np.divide(a,2,out = a)

array([0.5, 0.5, 0.5])

In [66]:
np.negative(a,out = a)

array([-0.5, -0.5, -0.5])

In [67]:
np.multiply(a,b,out = a)

array([-1.5, -1.5, -1.5])

In [68]:
# 第三十六题：用五种方法提取一个随机数组的整数部分
z = np.random.uniform(0,10,10)
print(z - z%1)
print(np.floor(z))
print(np.ceil(z) - 1)
print(z.astype(int))
print(np.trunc(z))

[8. 2. 5. 6. 4. 9. 9. 1. 3. 3.]
[8. 2. 5. 6. 4. 9. 9. 1. 3. 3.]
[8. 2. 5. 6. 4. 9. 9. 1. 3. 3.]
[8 2 5 6 4 9 9 1 3 3]
[8. 2. 5. 6. 4. 9. 9. 1. 3. 3.]


In [69]:
# 第三十七题
z = np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [70]:
# 第三十八题：通过考虑一个可生成10个整数的函数来构成一个数组
def generate():
    for x in range(10):
        yield x
        
z = np.fromiter(generate(),dtype = float, count = -1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [72]:
# 第三十九题：创建一个长度为10的随机向量，其值域从0到1，但不包括0和1
z = np.linspace(0,1,11,endpoint = False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [73]:
#第四十题
z = np.random.random(10)
z.sort()
print(z)

[0.21944602 0.38496483 0.53216665 0.67023397 0.73311872 0.74906918
 0.7634817  0.8595288  0.92196038 0.94038663]


In [74]:
# 第四十一题：对于一个小数组，如何用比np.sum更快的方式进行求和
z = np.arange(10)
np.add.reduce(z)

45

In [76]:
#第四十二题
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
c = np.array_equal(a,b)
print(c)

False


In [80]:
# 第四十三题：创建一个只读数组
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

In [82]:
# 第四十四题：将笛卡尔坐标系下的一个10x2的矩阵转化为极坐标形式
z = np.random.random((10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.66509046 0.71878122 0.89289793 0.61835557 0.83598443 1.01683147
 0.42585212 0.96330199 1.02818248 0.87767481]
[1.15014167 0.95732419 0.57207716 1.41199773 0.8362875  1.2418231
 1.19696389 1.44356784 0.33605151 0.8386069 ]


In [83]:
# 第四十五题
z = np.random.random(10)
z[z.argmax()] = 1
print(z)

[1.         0.48668185 0.43073852 0.9022343  0.23623316 0.06711135
 0.04602875 0.90721613 0.53030841 0.61594025]


In [84]:
# 第四十六题：创建一个结构化数组，并实现x和y坐标覆盖【0，1】x[0.1]区间
z = np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [86]:
# 第四十七题：给定两个数组x和y，构造Cauchy矩阵C    cij = 1(xi - yj)
x = np.arange(8)
y = x+0.5
c = 1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.1636371179666


In [87]:
# 第四十八题：打印每个numpy 标量类型的最小值和最大值
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [88]:
# 第四十九题
np.set_printoptions(threshold = np.nan)
z= np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [89]:
# 第五十题:给定标量时，如何找到数组中最接近标量的值
z = np.arange(100)
v  =np.random.uniform(0,100)
index = (np.abs(z - v)).argmin()
print(z[index])

99
